config/routes.rb
Rails.application.routes.draw do

  resources :feeds do
      resources :entries, only: [:index, :show]
  end

  resources :entries, only: [:index]

  root 'feeds#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action :set_feed, :if => proc {params[:feed_id].present?}, only: :index

  def index
    if params[:q]
      @entries = Entry.ransack(params[:q]).result(distinct: true)
    else
      @entries = @feed.entries.order('published desc')
    end
  end

  def show
    @entry = @feed.entries.find(params[:id])
  end

  private
  def set_feed
    @feed = Feed.find(params[:feed_id])
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @q = Entry.ransack
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/entries/index.html.erb
<div class="container">

  <%= link_to feeds_path, :class => "mdl-chip mdl-chip--contact" do %>
    <span>
      <span class="mdl-chip__contact mdl-color--teal">🙆</span>
      <span class="mdl-chip__text">Sportify</span>
    </span>
  <% end%>

  <div class="demo-list-action mdl-list">
    <% @entries.each do |entry| %>
      <div class="mdl-list__item">
        <span class="mdl-list__item-primary-content">
          <% if entry.ogp_image.present? %>
            <%= image_tag entry.ogp_image, style: "max-width: 100px;", class: "material-icons mdl-list__item-avatar"%>
          <% end %>
          <% if entry.content.present? %>
            <span><%= link_to entry.title, feed_entry_path(entry.feed, entry)%> - <i> published <%= time_ago_in_words(entry.published) %> ago.</i></span>
          <% else %>
            <span><%= link_to entry.title, entry.url%> - <i> published <%= time_ago_in_words(entry.published) %> ago.</i></span>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>

</div>

app/views/entries/show.html.erb
<div class="container">
  <h3><%= link_to @entry.title, @entry.url %></h3>
  <i>published on <%= @entry.published %> by <%= @entry.author %></i>
  <p>
    <% if @entry.ogp_image.present? %>
      <%= image_tag @entry.ogp_image, style: "max-width: 200px;"%>
    <% end %>
    <%= @entry.content.to_s.html_safe %>
  </p>
</div>

app/views/feeds/_form.html.erb
<%= form_for(feed) do |f| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<button class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored "><%= link_to "add", new_feed_path, class: "material-icons" %></button>
<br>
<br>

<%= search_form_for @q, url: entries_path, method: :get do |f| %>

  # Search if the name field contains...
  <%= f.label :title %>
  <%= f.search_field :title_start %>
  <%= f.submit %>
<% end %>

<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Name</th>
      <th class="mdl-data-table__cell--non-numeric">Url</th>
      <th class="mdl-data-table__cell--non-numeric">Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td class="mdl-data-table__cell--non-numeric"><%= link_to feed.name, feed_path(feed) %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= feed.url %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= feed.description %></td>
        <td><%= link_to 'Show Entries', feed_entries_path(feed), class: "mdl-button mdl-button--raised mdl-button--colored" %></td>

        <td><%= link_to 'Edit', edit_feed_path(feed), class: "mdl-button mdl-button--raised" %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' }, class: "mdl-button mdl-button--raised"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feed.description %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sportify</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>